### ISSUE TITLE
[Feature Request] Looking for a function like save_variable_instances, but saves as OTF or TTF instead of WOFF.

### ISSUE THREAD

**Issue by fmotion1** [fabiocaccamo/python-fontbro#137]
Apologies if this is already possible. But I'm trying to find a way to bounce all variable instances to TTFs/OTFs. 

FontTools can do this one at a time:

`Fonttools varLib.mutator ./font.ttf wght=400 wdth=85`

But I can't find a solution that does it all in one go.

Any help appreciated!

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/python-fontbro/issues/137">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/python-fontbro/issues/137/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/python-fontbro/issues/137/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@fmotion1 what you're asking for is the default behaviour of the `save_variable_instances` method, then `.woff2` and `.woff` files can be generated too if needed using the apposite arguments.
