### ISSUE TITLE
Certain fonts crash get_characters_count()

### ISSUE THREAD

**Issue by seproDev** [fabiocaccamo/python-fontbro#48]
**Python version**
3.10.9

**Package version**
0.14.4

**Current behavior (bug description)**
Calling `get_characters_count()` on [this](https://github.com/fabiocaccamo/python-fontbro/files/10480255/test.zip) font crashes fontbro.
Stacktrace:
```
Traceback (most recent call last):
  File "C:\Users\User\Desktop\fonts\test.py", line 4, in <module>
    font.get_characters_count()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbro\font.py", line 308, in get_characters_count
    return len(list(self.get_characters(ignore_blank=ignore_blank)))
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbro\font.py", line 268, in get_characters
    for code, char_name in cmap.items():
AttributeError: 'NoneType' object has no attribute 'items'
```
The problem seems to be that fontTools' `getBestCmap` does not return any cmap even though a cmap (platform ID 3, encoding ID 5) is present.
I know too little about the inner workings of fontTools, to know if this should be considered a bug there or if fontbro should handle this more gracefully.

**Comment by seproDev** [comment]
I guess if no "best" cmap table is available, accessing the first one directly with `font["cmap"].tables[0]` would be possible.
I'll create an issue at the fontTools repo to see if they are interested in adjusting the `getBestCmap` function.

**Comment by fabiocaccamo** [comment]
@seproDev I see now that what you are looking for (platform ID 3, encoding ID 5) is not in the default cmapPreferences:
https://github.com/fonttools/fonttools/blob/c30a6355ffdf7f09d31e7719975b4b59bac410af/Lib/fontTools/ttLib/tables/_c_m_a_p.py#L78

**Comment by seproDev** [comment]
Was just writing something up for the fonttools repo and noticed that the [documentation](https://fonttools.readthedocs.io/en/latest/ttLib/ttFont.html#fontTools.ttLib.ttFont.TTFont.getBestCmap) says that `getBestCmap` only returns unicode cmaps, so this is working as intended as (3, 5) is Wansung encoding.
Without knowing a whole lot about how this function is used in other projects, I could imagine that returning non unicode cmaps here could cause problems.

**Comment by fabiocaccamo** [comment]
Yes, as you can see the tuple `(3, 5)` is not listed in the `cmapPreferences`.
The only solution I could provide on this side is to accept a `cmapPreferences` argument for overriding the default values used by `fontTools`.

**Comment by seproDev** [comment]
Wouldn't the `get_characters` method then be wrong, since it would interpret Wansung encoded characters as unicode?
Not 100% sure how this all works.
On my test branch, I decided to just throw an exception https://github.com/seproDev/python-fontbro/commits/fixes

**Comment by fabiocaccamo** [comment]
I agree with the idea to raise an Exception.

**Comment by fabiocaccamo** [comment]
@seproDev can I add the `.ttf` file you attached here to the test suite?

**Comment by seproDev** [comment]
I am unsure about the license of the font I initially uploaded.
Looking around, the [wine version of the MS symbol font](https://github.com/wine-mirror/wine/blob/master/fonts/symbol.ttf) licensed under LGPL 2.1 exhibits a similar issue, though here the cmap is (1, 0) (Macintosh Roman). I think for the purpose of a test case, LGPL 2.1 should be fine.

What do you think of adding a method to get the list of cmaps with a short description of what the platform/encoding ID means?
Something like this:
```python
font.get_cmap_tables()
> [{'platformID': 3, 'platEncID': 5, 'description': 'Windows, Wansung'}]
```

The full list of IDs can be found [here](https://learn.microsoft.com/en-us/typography/opentype/spec/cmap#platform-ids).

**Comment by fabiocaccamo** [comment]
@seproDev the purpose of this library is to provide an high level interface for common operations.
The change you suggested could be useful indeed, but I think that the right place for it would be inside `fontTools`. 

You could try to submit a PR to `fontTools`.

**Comment by seproDev** [comment]
@fabiocaccamo Fair point. I think this issue can be closed then. Thank you.

I will likely analyze my entire font collection of ~2M fonts with fontbro. If I encounter any bugs, I will create an issue or PR either here or at the fontTools repo, whichever seems more fitting.

**Comment by fabiocaccamo** [comment]
Cool!! Let me know if you find any issue or if there is some common operation that could be added to this library.
