### ISSUE TITLE
Add `from_collection()` class method (loading of TTC/OTC collections).

### ISSUE THREAD

**Issue by seproDev** [fabiocaccamo/python-fontbro#49]
Currently, TTC/OTC font collections can't be parsed. As an example here, [cambria.ttc](https://github.com/fabiocaccamo/python-fontbro/files/10504419/cambria.zip).
```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbro\font.py", line 231, in _init_with_filepath
    self._ttfont = TTFont(self._filepath, lazy=self._lazy)
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\fontTools\ttLib\ttFont.py", line 147, in __init__
    self.reader = SFNTReader(file, checkChecksums, fontNumber=fontNumber)
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\fontTools\ttLib\sfnt.py", line 60, in __init__
    raise TTLibError("specify a font number between 0 and %d (inclusive)" % (numFonts - 1))
fontTools.ttLib.TTLibError: specify a font number between 0 and 1 (inclusive)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\fonts\main.py", line 9, in <module>
    result = analyze_font(str(file))
  File "C:\Users\User\Desktop\fonts\analyze_font.py", line 28, in analyze_font
    font = fontbro.Font(filename)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbro\font.py", line 220, in __init__
    self._init_with_filepath(filepath, lazy=lazy)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbro\font.py", line 234, in _init_with_filepath
    raise ValueError(f"Invalid font at filepath: '{filepath}'.")
ValueError: Invalid font at filepath: 'samples\cambria.ttc'.
```

Potential solutions I can see:
 - Expose the `fontNumber` argument from the TTFont constructor (or just **kwargs)
 - Introduce a new class for font collections

<a href="https://dashboard.polar.sh/fabiocaccamo/python-fontbro/issues/49">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/fabiocaccamo/python-fontbro/issues/49/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/fabiocaccamo/python-fontbro/issues/49/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
For reference: https://github.com/fonttools/fonttools/issues/1664

**Comment by seproDev** [comment]
Also for reference, this is the code I used to get the number of fonts in a collection:
```python
try:
    with open(filename, "rb") as f:
        headers = fontTools.ttLib.sfnt.readTTCHeader(f)
except fontTools.ttLib.TTLibError:
    # Not a collection
    return None
number_of_fonts = headers.numFonts
```

**Comment by fabiocaccamo** [comment]
Cool, thank you!

**Comment by fabiocaccamo** [comment]
UPDATE: it's possible to pass `fontNumber` to the constructor using `kwargs`.

**Comment by fabiocaccamo** [comment]
@seproDev by upgrading to `0.16.0` version it's possible to get all fonts in a collection as `fontbro.Font` objects using `Font.from_collection(filepath)` class method:
https://github.com/fabiocaccamo/python-fontbro#from_collection

**Comment by seproDev** [comment]
Oh, very nice. Thank you!
I didn't know fonttools had a `TTCollection` class. Sometimes it helps to read the docs 🙃
