### ISSUE TITLE
Certain fonts crash get_features()

### ISSUE THREAD

**Issue by seproDev** [fabiocaccamo/python-fontbro#50]
**Python version**
3.10.9

**Package version**
0.14.4

**Current behavior (bug description)**

Calling `get_features()` on [this](https://github.com/fabiocaccamo/python-fontbro/files/10505700/LeagueGothic-Regular.zip) font crashes fontbro.
Stacktrace:
```
Traceback (most recent call last):
  File "C:\Users\User\Desktop\fonts\main.py", line 24, in <module>
    font.get_features()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbro\font.py", line 319, in get_features
    features_tags = self.get_features_tags()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbro\font.py", line 338, in get_features_tags
    feature_record = table.FeatureList.FeatureRecord or []
AttributeError: 'NoneType' object has no attribute 'FeatureRecord'
```

Looks like `FeatureList` can be None. This only affects the GSUB and not the GPOS table.

**Comment by fabiocaccamo** [comment]
Could you provide also a font to use for adding a test case?

**Comment by seproDev** [comment]
The [file I linked](https://github.com/fabiocaccamo/python-fontbro/files/10505700/LeagueGothic-Regular.zip) is fine to use as a test case, as it is an older version of [League Gothic](https://fonts.google.com/specimen/League+Gothic/about) which is licensed under OFL.

**Comment by fabiocaccamo** [comment]
Sorry, I totally missed the link in the first message! Thank you
