### ISSUE TITLE
font.rename produce wrong changes

### ISSUE THREAD

**Issue by HugoJourdan** [fabiocaccamo/python-fontbro#62]
**Python version**
3.11

**Package version**
0.14.5)

**Current behavior (bug description)**

Using font.rename seems to produce wrong changes (I also try with style_name arg and same problems happened):
Here is screenshot with source name table and the one produce with font.rename where I tried to replace `ABC` by `Hugo`
![Screenshot 2023-03-16 at 14 12 01](https://user-images.githubusercontent.com/76793951/225627517-45db94a8-65c8-4ef6-97c6-07d4039962db.png)

All theses names are wrong : 
- fontFamily : Hugo Test Thin Thin
- fullName : Hugo Test Thin Thin Regular
- postScriptName : HugoTestThin-Thin
- preferredFamily : Hugo Test Thin
- uniqueID : 1.000;UKWN;ABCTest-Thin

They should look like : 
- fontFamily : Hugo Test Thin
- fullName : Hugo Test Thin 
- postScriptName : HugoTest-Thin
- preferredFamily : Hugo Test
- uniqueID : 1.000;UKWN;HugoTest-Thin

Here is the code I used :

``` python
font = fontbro.Font(filePath)
family_name = font.get_name(key=font.NAME_FAMILY_NAME)
family_name = family_name.replace("ABC", "Hugo")
font.rename(family_name=family_name)
font.save(filepath=None, overwrite=True)
```

**Comment by HugoJourdan** [comment]
uniqueID contains the postScriptName, so if the postScriptName is changed, why wouldn't uniqueID be changed as well?

**Comment by fabiocaccamo** [comment]
@HugoJourdan could you provide the font to use it for tests? (You can drop the glyphs).

**Comment by HugoJourdan** [comment]
Of course !
[ABC Test.zip](https://github.com/fabiocaccamo/python-fontbro/files/11031186/ABC.Test.zip)

**Comment by fabiocaccamo** [comment]
@HugoJourdan the problem is that your family name includes the subfamily name, try this:

```python
font = Font(filepath)
family_name = font.get_name(key=Font.NAME_FAMILY_NAME)
family_name = family_name.rstrip("Thin").strip()
family_name = family_name.replace("ABC", "Hugo")
font.set_name(Font.NAME_FAMILY_NAME, family_name)
font.rename(family_name=family_name, style_name="Thin")
print(font.get_names())
```

Output: 

```python
{
    "family_name": "Hugo Test Thin",
    "full_name": "Hugo Test Thin Regular",
    "postscript_name": "HugoTest-Thin",
    "subfamily_name": "Regular",
    "typographic_family_name": "Hugo Test",
    "typographic_subfamily_name": "Thin",
    "unique_identifier": "1.000;UKWN;HugoTest-Thin",
    "version": "Version 1.000;Glyphs 3.1.2 (3151)",
    "wws_family_name": "Hugo Test",
    "wws_subfamily_name": "Thin"
}
```

---

> And I notice that uniqueID has not been changed, I think it should also be changed with font.rename.

Thank you for reporting this, I fixed it and it will be available in the next release.

**Comment by fabiocaccamo** [comment]
Fixed postscript name renaming in unique identifier in `0.14.6` version.

**Comment by HugoJourdan** [comment]
> @HugoJourdan the problem is that your family name includes the subfamily name, try this:
> 
> ```python
> font = Font(filepath)
> family_name = font.get_name(key=Font.NAME_FAMILY_NAME)
> family_name = family_name.rstrip("Thin").strip()
> family_name = family_name.replace("ABC", "Hugo")
> font.set_name(Font.NAME_FAMILY_NAME, family_name)
> font.rename(family_name=family_name, style_name="Thin")
> print(font.get_names())
> ```
> 
> Output:
> 
> ```python
> {
>     "family_name": "Hugo Test Thin",
>     "full_name": "Hugo Test Thin Regular",
>     "postscript_name": "HugoTest-Thin",
>     "subfamily_name": "Regular",
>     "typographic_family_name": "Hugo Test",
>     "typographic_subfamily_name": "Thin",
>     "unique_identifier": "1.000;UKWN;HugoTest-Thin",
>     "version": "Version 1.000;Glyphs 3.1.2 (3151)",
>     "wws_family_name": "Hugo Test",
>     "wws_subfamily_name": "Thin"
> }
> ```
> 
> > And I notice that uniqueID has not been changed, I think it should also be changed with font.rename.
> 
> Thank you for reporting this, I fixed it and it will be available in the next release.

It's seems that double style name was a issus from my side, not from font.rename, sorry.

**Comment by HugoJourdan** [comment]
You are right, but I think using IDs 16 and 17 is more "logical" than using IDs 1 and 2. 
It's seems that GlyphsApp and fontmake use IDs 16 and 17 when doing exports.

**Comment by fabiocaccamo** [comment]
> It's seems that GlyphsApp and fontmake use IDs 16 and 17 when doing exports.

Could you verify this please?

**Comment by HugoJourdan** [comment]
I just verified it and can confirm they use IDs 16 and 17.
Here are exports made with Glyphs and Fontmake : [Exports.zip](https://github.com/fabiocaccamo/python-fontbro/files/11054652/Exports.zip)

**Comment by fabiocaccamo** [comment]
Thank you very much for having checked it, I will fix it tomorrow or in the weekend.

**Comment by fabiocaccamo** [comment]
@HugoJourdan you can upgrade to `0.14.7` version.
